// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("loghouse")
	ScopeName = "otelcol/loghouse"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
